import "./globals.css";
import { merriweather } from "./ui/fonts";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.className}`}
      >
        {children}
      </body>
    </html>
  );
}
